#!/usr/bin/env bash
echo "Starting compressed code build..."
echo "Cleaning out build directory..."
rm -rf ./web/build
echo "Build i18n files..."
./tasks/i18n
echo "Building code..."
./tasks/webpack-compressed
